name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg ARCH=rocm --build-arg CONFIG=standard-rocm.yaml -f docker/Dockerfile-rocm-mi250mi300_torch251 . --tag milabennch-rocm:mi250mi300_torch251-$(date +%s)
